import dayjs from 'dayjs/esm';

import { IRegVenta, NewRegVenta } from './reg-venta.model';

export const sampleWithRequiredData: IRegVenta = {
  id: '3431caf2-afc1-42b2-bf3b-343caa50548e',
  periodo: 'synthesizing Gourde',
  cuo: 'Strategist Overpass',
  fecEmiComp: dayjs('2022-08-25T10:30'),
  tipComp: 'copy Buckinghamshire global',
  nroSerieComp: 'Hat Concrete',
  nroComp: 'virtual deliverables Salad',
  tipDocCli: 'Associate Fall bottom-line',
  nroDocCli: 'initiative context-sensitive',
  apeRazSocCli: 'parse Granite Handcrafted',
  baseImpOperGrav: 34503,
  dsctoBaseImp: 4110,
  igvIpm: 14085,
  dsctoIgvIpm: 24092,
  impOpeExo: 41657,
  impTotOpeInafec: 93242,
  importeTotalComp: 92348,
  codMoneda: 'strategy throughput FTP',
  tipCambio: 63091,
  indDel: true,
  fecCrea: dayjs('2022-08-24T23:04'),
  usuCrea: 'Designer azure auxiliary',
  ipCrea: 'Gorgeous Auto',
};

export const sampleWithPartialData: IRegVenta = {
  id: '309448f1-e5f0-48ef-8b9e-a504db39656b',
  periodo: 'navigating Algeria',
  cuo: 'driver Technician Frozen',
  fecEmiComp: dayjs('2022-08-25T16:16'),
  fecVencComp: dayjs('2022-08-25T10:36'),
  tipComp: 'Grenada Sports',
  nroSerieComp: 'redundant',
  nroComp: 'Barthelemy',
  consoDia: 'capacitor transmitting',
  tipDocCli: 'indexing ROI',
  nroDocCli: 'interface',
  apeRazSocCli: 'Optimization',
  baseImpOperGrav: 70310,
  dsctoBaseImp: 5717,
  igvIpm: 37601,
  dsctoIgvIpm: 93436,
  impOpeExo: 31085,
  impTotOpeInafec: 68781,
  impSecCons: 672,
  impVentArroz: 87664,
  importeTotalComp: 54092,
  codMoneda: 'quantifying payment',
  tipCambio: 73736,
  fecEmiModif: dayjs('2022-08-25T12:29'),
  tipCompModif: 'North payment Buckinghamshire',
  nroCompModif: 'niches Marketing',
  estadoOperaCancMp: 'Borders',
  campoLibre: 'Idaho interactive',
  formPago: 'Brook Account navigating',
  indDel: true,
  fecCrea: dayjs('2022-08-25T11:20'),
  usuCrea: 'generation Bike',
  ipCrea: 'Profit-focused Specialist black',
  fecModif: dayjs('2022-08-24T20:17'),
};

export const sampleWithFullData: IRegVenta = {
  id: '2f713e08-ec97-4c96-8f99-cef655165e6d',
  periodo: 'context-sensitive indexing',
  cuo: 'withdrawal Ouguiya',
  asientContab: 'invoice Dynamic',
  fecEmiComp: dayjs('2022-08-25T01:05'),
  fecVencComp: dayjs('2022-08-24T22:49'),
  tipComp: 'Unbranded',
  nroSerieComp: 'payment',
  nroComp: 'empowering 1080p',
  consoDia: 'parsing',
  tipDocCli: 'driver visualize Computers',
  nroDocCli: 'synthesizing Direct',
  apeRazSocCli: 'Facilitator',
  valFacExpor: 68867,
  baseImpOperGrav: 8041,
  dsctoBaseImp: 3788,
  igvIpm: 69455,
  dsctoIgvIpm: 31088,
  impOpeExo: 15235,
  impTotOpeInafec: 76485,
  impSecCons: 88054,
  baseImpArroz: 7411,
  impVentArroz: 8214,
  otrosNoBaseImp: 25718,
  importeTotalComp: 18073,
  codMoneda: 'yellow',
  tipCambio: 80993,
  fecEmiModif: dayjs('2022-08-25T13:19'),
  tipCompModif: 'application syndicate Crest',
  nroSerieCompModif: 'Ireland',
  nroCompModif: 'wireless',
  identContrato: 'exploit Concrete',
  errTipUno: 'compressing',
  indCompVancMp: 'Fall generate',
  estadoOperaCancMp: 'Road Rapid back',
  campoLibre: 'navigating',
  formPago: 'Future',
  moneda: 'open-source Principal',
  indDel: false,
  fecCrea: dayjs('2022-08-25T05:53'),
  usuCrea: 'gold',
  ipCrea: 'Auto actuating',
  fecModif: dayjs('2022-08-25T06:16'),
  usuModif: 'Bedfordshire Avenue Data',
  ipModif: 'driver Concrete Ferry',
};

export const sampleWithNewData: NewRegVenta = {
  periodo: 'mesh',
  cuo: 'Iraq cross-media',
  fecEmiComp: dayjs('2022-08-24T19:47'),
  tipComp: 'Delaware monetize fresh-thinking',
  nroSerieComp: 'Automated Public-key 1080p',
  nroComp: 'enable',
  tipDocCli: 'Christmas Somalia Right-sized',
  nroDocCli: 'North',
  apeRazSocCli: 'Ameliorated hack',
  baseImpOperGrav: 23168,
  dsctoBaseImp: 89905,
  igvIpm: 25864,
  dsctoIgvIpm: 77890,
  impOpeExo: 99755,
  impTotOpeInafec: 43468,
  importeTotalComp: 74040,
  codMoneda: 'iterate',
  tipCambio: 83994,
  indDel: false,
  fecCrea: dayjs('2022-08-25T11:22'),
  usuCrea: 'bypassing plug-and-play Legacy',
  ipCrea: 'methodologies cross-platform',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
